---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    elastic-app: kibana
  name: kibana
  namespace: loging
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: kibana
  template:
    metadata:
      labels:
        elastic-app: kibana
    spec:
      containers:
        - name: kibana
          image: hub.qoros.com/library/kibana:7.2.0
          ports:
            - containerPort: 5601
              protocol: TCP
          env:
            - name: "ELASTICSEARCH_HOSTS"
              value: "http://elasticsearch-service-http:9200"
      #tolerations:
      #  - key: node-role.kubernetes.io/master
      #    effect: NoSchedule

---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: kibana
  name: kibana-service
  namespace: loging
spec:
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30002
  selector:
    elastic-app: kibana
  type: NodePort
