---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch-admin
  namespace: loging
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-admin
  labels:
    elastic-app: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: elasticsearch-admin
    namespace: loging
 

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    elastic-app: elasticsearch
    role: master
  name: elasticsearch-master
  namespace: loging
spec:
  serviceName: es-master
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        elastic-app: elasticsearch
        role: master
    spec:
      #将持久卷声明  
      #volumes:
      # - name: pv-storage-elastic-master
      #   persistentVolumeClaim:
      #     claimName: pvc-es-master     
      #nodeSelector:
      #  es: enable
      containers:
        - name: elasticsearch-master
          #image: elasticsearch:7.6.2
          image: hub.qoros.com/library/elasticsearch:7.2.0
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                #command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data;"]
                command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144"]
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            #修改es默认的数据存储目录，否则多个节点同时写一个目录es权限不允许                                           
            - name: "path.data"
              value: "/usr/share/elasticsearch/data/$(MY_POD_NAME)"            
            - name: "cluster.name"
              value: "elasticsearch-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.seed_hosts" #7.x的配置方式
              value: "elasticsearch-discovery"
            - name: "node.master"
              value: "true"
            - name: "node.data"
              value: "false"
            - name: "node.ingest"
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms1024m -Xmx1024m"
            - name: "cluster.initial_master_nodes"
              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
          securityContext:
            privileged: true
          #将持久卷映射为数据目录的父目录  
          volumeMounts:
            - name: pv-storage-elastic-master
              mountPath: /usr/share/elasticsearch/data/            
      imagePullSecrets:
      - name: aliyun-secret            
      serviceAccountName: elasticsearch-admin
      #tolerations:
      #  - key: node-role.kubernetes.io/master
      #    effect: NoSchedule
      #initContainers:
      #- name: chown
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sh","-c","chmod -R 777 /usr/share/elasticsearch/data"]
      #  securityContext:
      #    privileged: true
      #  volumeMounts:
      #  - name: pv-storage-elastic-data
      #    mountPath: /usr/share/elasticsearch/data
      #- name: vm
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sysctl","-w","vm.max_map_count=262144"]
      #  securityContext:
      #    privileged: true
      #  env:
      #    - name: "bootstrap.memory_lock"
      #      value: "true"
      #- name: ulimit
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sh","-c","ulimit -l unlimited"]
      #  securityContext:
      #    privileged: true
  volumeClaimTemplates:
   - metadata:
       name: pv-storage-elastic-master
     spec:
       accessModes: ["ReadWriteOnce"]
       storageClassName: "managed-nfs-storage"
       resources:
         requests:
           storage: 1Gi
 
 
---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch-discovery
  namespace: loging
spec:
  #type: ExternalName
  #externalName: elasticsearch-discovery.loging.svc.cluster.local
  publishNotReadyAddresses: true
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    elastic-app: elasticsearch
    role: master

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    elastic-app: elasticsearch
    role: data
  name: elasticsearch-data
  namespace: loging
spec:
  serviceName: es-data  
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: elasticsearch
  template:
    metadata:
      labels:
        elastic-app: elasticsearch
        role: data
    spec:
      #将es-data持久卷声明
      #volumes:
      # - name: pv-storage-elastic-data
      #   persistentVolumeClaim:
      #     claimName: pvc-es-data 
      #nodeSelector:
      #  es: enable
      containers:
        - name: elasticsearch-data
          #image: elasticsearch:7.6.2
          image: hub.qoros.com/library/elasticsearch:7.2.0
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                #command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data;"]
                command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144"]
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            #修改es默认的数据存储目录，否则多个节点同时写一个目录es权限不允许                  
            - name: "path.data"
              value: "/usr/share/elasticsearch/data/$(MY_POD_NAME)"
            - name: "cluster.name"
              value: "elasticsearch-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.seed_hosts"
              value: "elasticsearch-discovery"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms1024m -Xmx1024m"
          securityContext:
            privileged: true
          #将持久卷映射到数据目录的父目录  
          volumeMounts:
            - name: pv-storage-elastic-data
              mountPath: /usr/share/elasticsearch/data/
      # imagePullSecrets:
      # - name: aliyun-secret          
      serviceAccountName: elasticsearch-admin
      #tolerations:
      #  - key: node-role.kubernetes.io/master
      #    effect: NoSchedule
      #initContainers:
      #- name: chown
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sh","-c","chmod -R 777 /usr/share/elasticsearch/data"]
      #  securityContext:
      #    privileged: true
      #  volumeMounts:
      #  - name: pv-storage-elastic-data
      #    mountPath: /usr/share/elasticsearch/data
      #- name: vm
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sysctl","-w","vm.max_map_count=262144"]
      #  securityContext:
      #    privileged: true
      #  env:
      #    - name: "bootstrap.memory_lock"
      #      value: "true"
      #- name: ulimit
      #  image: hub.qoros.com/library/busybox:1.28
      #  command: ["sh","-c","ulimit -l unlimited"]
      #  securityContext:
      #    privileged: true
  volumeClaimTemplates:
   - metadata:
       name: pv-storage-elastic-data
     spec:
       accessModes: ["ReadWriteOnce"]
       storageClassName: "managed-nfs-storage"
       resources:
         requests:
           storage: 1Gi

---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch-service
  name: elasticsearch-service-http
  namespace: loging
spec:
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 32000
  selector:
    elastic-app: elasticsearch
  type: NodePort
 
---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch-service
  name: elasticsearch-service-tcp
  namespace: loging
spec:
  ports:
    - port: 9300
      targetPort: 9300
      nodePort: 32100
  selector:
    elastic-app: elasticsearch
  type: NodePort
---
