---
- name: '配置k8s-node脚本'
  copy: src=files/03_k8s-bin-node-calico.sh dest=/tmp/03_k8s-bin-node-calico.sh mode=0700 owner=root group=root force=yes

- name: 'k8s安装包'
  copy: src=files/kubernetes-server-linux-amd64.tar.gz dest=/tmp/kubernetes-server-linux-amd64.tar.gz mode=0644 owner=root group=root force=yes

- name: 'pause安装包'
  copy: src=files/pause-amd64.tar dest=/tmp/pause-amd64.tar mode=0644 owner=root group=root force=yes

- name: 'calico kube-controllers安装包'
  copy: src=files/calico_kube-controllers.tar dest=/tmp/calico_kube-controllers.tar mode=0644 owner=root group=root force=yes

- name: 'calico node安装包'
  copy: src=files/calico_node.tar dest=/tmp/calico_node.tar mode=0644 owner=root group=root force=yes

- name: 'calico cni安装包'
  copy: src=files/calico_cni.tar dest=/tmp/calico_cni.tar mode=0644 owner=root group=root force=yes
