---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oap
  namespace: skywalking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oap
      release: skywalking
  template:
    metadata:
      labels:
        app: oap
        release: skywalking
    spec:
      serviceAccountName: skywalking-oap
      containers:
        - name: oap
          #image: apache/skywalking-oap-server:8.3.0-es7
          image: hub.qoros.com/library/skywalking-oap-server:8.5.0-es7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11800
              name: grpc
            - containerPort: 12800
              name: rest
          volumeMounts:
          - name: application-config
            mountPath: /skywalking/config/application.yml
            subPath: application.yml
            readOnly: false
          - name: alarm-settings-config
            mountPath: /skywalking/config/alarm-settings.yml
            subPath: alarm-settings.yml
            readOnly: false
      #    env:
      #    - name: SW_STORAGE
      #      value: elasticsearch7
      #    - name: SW_STORAGE_ES_CLUSTER_NODES
      #      value: 10.58.133.11:30015
      volumes:
        - name: application-config
          configMap:
            name: application-config 
        - name: alarm-settings-config
          configMap:
            name: alarm-settings-config 
---
apiVersion: v1
kind: Service
metadata:
  name: oap
  namespace: skywalking
  labels:
    service: oap
spec:
  ports:
    - port: 12800
      name: rest
      nodePort: 30128
    - port: 11800
      name: grpc
      nodePort: 30118
  type: NodePort
  selector:
    app: oap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: skywalking
  labels:
    app: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          #image: apache/skywalking-ui:6.6.0
          image: hub.qoros.com/library/skywalking-ui:6.6.0
          ports:
            - containerPort: 8080
              name: page
          env:
            - name: SW_OAP_ADDRESS
              value: oap.skywalking:12800
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: skywalking
  labels:
    service: ui
spec:
  ports:
    - port: 8080
      name: page
      nodePort: 31008
  type: NodePort
  selector:
    app: ui
