apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsp-gateway-v2  ##需要更改delployment名称
  namespace: tsp-qoros-test
  labels:
    tsp-gateway: tsp-gateway  ##需要更改label
spec:
  replicas: 2
  selector:
    matchLabels:
      tsp-gateway: tsp-gateway   ##需要更改label
  template:
    metadata:
      labels:
        tsp-gateway: tsp-gateway   ##需要更改label
    spec:
      #nodeSelector:
        #tsp-gateway: tsp-gateway
      imagePullSecrets:
        - name: registry-secret-qoros  ##暂定这个，到时候需要根据运维工程师创建的密码对象来调整
      initContainers:
        - image: hub.qoros.com/library/skywalking-agent:8.5.0
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            [
              "-c",
              "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent",
            ]
          volumeMounts:
            - mountPath: /skywalking/agent
              name: skywalking-agent
      containers:
        - name: tsp-gateway-v2  ##需要更改
          image: hub.qoros.com/tsp-qoros-prod/tsp-gateway-v2    ##需要更改的images
          ports:
            - containerPort: 8751  ##需要更改端口
              name: container-port
            - containerPort: 1098  ##需要更改端口
              name: jmx-port
          resources:
            limits:
              cpu: 2
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 2048Mi
          readinessProbe:              #就绪探针
            httpGet:
              path: /actuator/health  ##需要确认微服务健康检查路径
              port: 8751  ##需要更改端口
            initialDelaySeconds: 20    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 10         #超时时间设置
            failureThreshold: 5        #探测失败的重试次数
          livenessProbe:               #存活探针
            httpGet:
              path: /actuator/health   ##需要确认微服务健康检查路径
              port: 8751  ##需要更改端口
            initialDelaySeconds: 120    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 5          #超时时间设置
            failureThreshold: 3        #探测失败的重试次数
          command: ["java"]
          args: ["-jar","-Xms2048m","-Xmx2048m","-Xmn512m","-XX:MaxPermSize=512m","-XX:+UseParNewGC","-XX:+UseConcMarkSweepGC","-Dsun.jnu.encoding=UTF-8","-Dfile.encoding=UTF-8","-Djava.security.egd=file:/dev/./urandom","/app.jar","--spring.profiles.active=test","--spring.cloud.config.label=test",]
          volumeMounts:
            - name: skywalking-agent
              mountPath: /usr/skywalking/agent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: tsp-gateway-v2
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: 10.58.133.2:30118
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service ##需要更改服务名
  namespace: tsp-qoros-test
  labels:
    tsp-gateway: tsp-gateway   ##需要更改label
spec:
  #clusterIP: None
  type: NodePort
  ports:
    - name: tsp-gateway-v1
      port: 8751
      nodePort: 30008
  selector:
    tsp-gateway: tsp-gateway
